# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcpospoc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos_profile',
            old_name='isStaff',
            new_name='is_staff',
        ),
    ]
