# Generated by Django 2.1 on 2018-08-29 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('brand_name', models.CharField(max_length=45)),
                ('category', models.CharField(choices=[('AUTOMOTIVE', 'Automotive'), ('BEAUTY', 'Beauty'), ('BOOKS', 'Books'), ('CELLPHONES', 'Cell Phones'), ('CONSUMER', 'Consumer'), ('GROCERY', 'Grocery'), ('SCIENTIFIC', 'Scientific'), ('INDUSTRIAL', 'Industrial')], default='CONSUMER', max_length=2)),
                ('subcategory', models.CharField(blank=True, max_length=45)),
                ('brand', models.CharField(blank=True, choices=[('PANASONIC', 'Panasonic'), ('SAMSUNG', 'Samsung'), ('ATUL', 'Atul'), ('NESTLE', 'Nestle'), ('ASTRALPIPES', 'Astral Pipes')], default='', max_length=2)),
                ('quantity', models.SmallIntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)])),
                ('isGst', models.BooleanField()),
            ],
        ),
    ]
