# Generated by Django 2.1 on 2018-08-29 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('posapp_be_users', '0002_auto_20180829_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_POS',
            field=models.BooleanField(default=True),
        ),
    ]
