version: '3'
services:
  axelor:
    image: axelor/aio-base
    build: .
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=443
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./volumes/var/lib/postgresql:/var/lib/postgresql
      - ./volumes/var/log/postgresql:/var/log/postgresql
      - ./volumes/var/lib/tomcat:/var/lib/tomcat
      - ./volumes/var/log/tomcat:/var/log/tomcat
